### ISSUE TITLE
regression in <FormatMessage> rendering in 0.3.15

### ISSUE THREAD

**Issue by yinquanteo** [globalizejs/react-globalize#61]
There appears to be a regression in <FormatMessage> rendering in 0.3.15 introduced in this commit https://github.com/globalizejs/react-globalize/commit/1a9765f8ccdb9b0d871cd4189de79814da4d31c6. 

This is the same chunk of code in my application but with different versions of react-globalize. 

(before react-globalize 0.3.15)
![before](https://cloud.githubusercontent.com/assets/349383/21408188/70a599c2-c788-11e6-8d5e-7746e2b5cbe2.gif)

(using react-globalize 0.3.15)
![after](https://cloud.githubusercontent.com/assets/349383/21408033/83c654ac-c787-11e6-8684-ee218f3d72e8.gif)

Here's the chunk of code that renders the buttons. 1 is plain text, 2 is text wrapped with FormatMessage, 3 is text using Globalize.formatMessage. You would expect the text in 3 cases to be exactly the same. However, as you can see from the gifs above, that's not the case for 0.3.15
 
```
    if (dataStatus === 'modify') {
      return (
        <div className={styles.buttonGroup} >
          <Button
            onClick={onCancelModifications}
            size='small'>
            1. Cancel
            2. <FormatMessage>Cancel</FormatMessage>
            3. {Globalize.formatMessage('Cancel')}
          </Button>
          <Button
            appearance='primary'
            className={styles.saveButton}
            onClick={this._handleSaveButtonClick}
            size='small'>
            1. Save changes
            2. <FormatMessage>Save changes</FormatMessage>
            3. {Globalize.formatMessage('Save changes')}
          </Button>
        </div>
      );
    } else if (dataStatus === 'read_only') {
      return (
        <div className={styles.buttonGroup}>
          <Button
            onClick={onAddUserAccessButtonClick}
            size='small'>
            1. Add access
            2. <FormatMessage>Add access</FormatMessage>
            3. {Globalize.formatMessage('Add access')}
          </Button>
          <Button
            className={styles.editAccessButton}
            onClick={onModifyUserAccessButtonClick}
            size='small'>
            1. Edit access
            2. <FormatMessage>Edit access</FormatMessage>
            3. {Globalize.formatMessage('Edit access')}
          </Button>
        </div>
      );
    } 
```

**Comment by necolas** [comment]
It's a little hard to understand from your example. Is it that the component doesn't update when the child text does? If you can submit a PR with a failing test case that would be a big help. Thanks

**Comment by necolas** [comment]
Yeah looks like a problem with `children` not updating

**Comment by rxaviers** [comment]
Thanks for investigating this further @necolas.

**Comment by necolas** [comment]
@yinquanteo should be fixed by #62

**Comment by yinquanteo** [comment]
thanks for the quick fix!

**Comment by rxaviers** [comment]
Finally released in 0.3.16.

**Comment by necolas** [comment]
Thanks. Please could you push 0.3.16 to GitHub too?

**Comment by kborchers** [comment]
I would do it but it looks like I can't cherry-pick the commit out of the tag (since the tags have a build commit we don't want in history) without changing the SHA and I'm not sure what that would do to the tag but my guess is nothing good. Probably have to wait fro @rxaviers to push that commit.

**Comment by rxaviers** [comment]
Sorry I did it in a rush. I'm traveling and will push the tag within a day (it's indeed detached and in another laptop). By the way, we need to automate the release process #63. :)

**Comment by rxaviers** [comment]
Just noticed the detached tag was pushed, so I believe everything should be fine. Just let me know in case it's missing something. Thanks
