### ISSUE TITLE
FormatMessage Element Replacement example has a typo

### ISSUE THREAD

**Issue by jphoang** [globalizejs/react-globalize#65]
The code sample in the `FormatMessage` Element Replacement example contains:
`[reactGlobalize]React Globalize[/reactGlobalize]`

but should be:
`[reactGlobalizeLink]React Globalize[/reactGlobalizeLink]`

**Comment by jphoang** [comment]
I fixed it here: https://github.com/globalizejs/react-globalize/pull/66

**Comment by rxaviers** [comment]
Thank you, merged.
