### ISSUE TITLE
Changing string variable names causes error in FormatMessage.apply

### ISSUE THREAD

**Issue by sieverk** [globalizejs/react-globalize#67]
Started seeing an error recently when updating some FormatMessage i18n strings that I haven't encountered before (in this context, at least). It appears that changing just the string content is fine, but when I start changing the variable names, I'm seeing the following error in production/staging:

```
Uncaught TypeError: Cannot read property 'apply' of undefined
    at Function.e.formatMessage.e.formatMessage
```

It's difficult to debug because everything works fine when running locally - the issue only crops up on staging/production builds. I tested four cases:

1. Change just the string content for a FormatMessage with no variables: `[myLink]FOO[/myLink]` -> `[myLink]FOOBAR[/myLink]`
**result = no error**

2. Change just the string content for a FormatMessage with variables: `[myLink]FOO {userName}[/myLink]` -> `[myLink]FOOBAR {userName}[/myLink]`
**result = no error**

3. Change just the variable name for a FormatMessage with variables: `[myLink]FOO {userName}[/myLink]` -> `[myLink]FOO {userNameTest}[/myLink]`
**result = error**

4. Change the variable name and string content for a FormatMessage with variables: `[myLink]FOO {userName}[/myLink]` -> `[myLink]FOOBAR {userNameTest}[/myLink]`
**result = error**

**Comment by necolas** [comment]
@rxaviers since this only happens with our production builds the root cause may lie in the compiler

**Comment by necolas** [comment]
This was caused by not importing `globalize` into the file that was using `react-globalize`.
