### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by necolas** [globalizejs/react-globalize#71]
Hi, please can we get a new version released as we need to use ce5d0a763c7e8f3631080c5be5297ac32a98a339, and add release/build instructions to the README so I/we can more easily cut new releases ourselves going forward. Thanks

**Comment by rxaviers** [comment]
Related issue:
- #63

**Comment by rxaviers** [comment]
Let's address the points I just made here https://github.com/globalizejs/react-globalize/pull/70/files before releasing.

**Comment by rxaviers** [comment]
> Let's address the points I just made here https://github.com/globalizejs/react-globalize/pull/70/files before releasing.

I've just implemented them via #72

**Comment by rxaviers** [comment]
Add release instructions until this is properly automated via #73

**Comment by rxaviers** [comment]
@necolas I've published `0.4.0-alpha.0`, please can you make sure it's working as you expect. Then, feel free to go ahead and make `0.4.0` or let me know if you have any questions.

**Comment by necolas** [comment]
Thanks, will do!

**Comment by paularmstrong** [comment]
✅ Verified working for us. Thanks @rxaviers! cc/ @necolas
